all: klasa
	# Done
klasa: klasa.cpp
	g++ klasa.cpp -o klasa -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_image -lallegro_primitives -lallegro_image -lallegro_font -lallegro_ttf
