all: bouncer przyciski
	# Done
bouncer: bouncer.cpp
	g++ bouncer.cpp -o bouncer -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf
przyciski: przyciski.cpp
	g++ przyciski.cpp -o przyciski -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf
