all:
	# Chwilowo makefile jest pusty.
	# Projekt możesz skompilować za pomocą dowolnego IDE np. Code Blocks
	# Pamiętaj o opcjach -std=c++11 -pthread i o zalinkowaniu bibliotek allegro5 oraz websockets 
