all: kolo
	# Done
kolo: kolo.cpp
	g++ kolo.cpp -o kolo -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_image -lallegro_primitives -lallegro_image -lallegro_font -lallegro_ttf


