all: elf
	# Done
elf: elf_driver.cpp
	g++ elf_driver.cpp -o elf -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_image -lallegro_primitives -lallegro_image -lallegro_font -lallegro_ttf -lallegro_dialog

