all: achtung_die_kurve
	# Done
achtung_die_kurve: achtung_die_kurve.cpp run.cpp
	g++ achtung_die_kurve.cpp -o achtung_die_kurve -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf -lwebsockets
