all: kolorysuper
	# Done
kolorysuper: kolorysuper.cpp
	g++ kolorysuper.cpp -o kolorysuper -I/opt/local/include/ -L/opt/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf
