all: 2048
	# Done
2048: 2048.cpp
	g++ 2048.cpp -o 2048 -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_image -lallegro_primitives -lallegro_image -lallegro_font -lallegro_ttf

